server:
  port: 80
spring:
  application:
    name: spring-boot-demo
management:
  endpoints:
    web:
      exposure:
        include: health, info, beans, env, mappings
customize:
  id: 21
  code: CODE
  enable: true
  credential:
    username: admin
    password: 123456
  credential-with-converter: another-admin, 123321
  string-list: 1, 2, 3
  another-string-list[0]: 5
  another-string-list[1]: 6
  another-string-list[2]: 7
  simple-string-list:
    - 7
    - 8
    - 9
  simple-map-list:
    - k1: v1
      k2: v2
      K3: v3
    - k1: v1
      k2: v2
      K3: v3
    - k7: v7
      k8: v8
      k9: v9
  simple-credential-list:
    - username: userInList01
      password: passInList01
    - username: userInList02
      password: passInList02
    - username: userInList03
      password: passInList03
  simple-credential-with-converter-list:
    - userInList07, passInList07
    - userInList08, passInList08
    - userInList09, passInList09
  boolean-map:
    key0: true
    key1: false
    key2: on
    key3: off
  string-map:
    key0: true
    key1: false
    key2: on
    key3: off
    key4: 1
    key5: 2
    key6: 01
    key7: 02
    key8: value1
    key9: value2
  map-map:
    key0:
      k1: v1
      k2: v2
    key1:
      k1: v1
      k2: v2
    key3:
      k2: v2
      k3: v3
  credential-map:
    key0:
      username: userInMap01
      password: passInMap01
    key1:
      username: userInMap02
      password: passInMap02
    key2:
      username: userInMap03
      password: passInMap03
  credential-with-converter-map:
    key0: userInMap07, passInMap07
    key1: userInMap08, passInMap08
    key2: userInMap09, passInMap09